version: '2'

services:
  proxy-service:
    image: unna/proxy-service
    ports:
      - "8080:8080"
    environment:
      # WARNING: the domainname *must* match the actual docker network name
      - REDIS_HOST=redis.fexco_default
      - REDIS_PORT=6379
      - HTTP_PORT=8080
      - BUG=bug
    depends_on:
      - redis
  redis:
    image: redis
